services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    expose:
      - "3001"
    env_file:
      - apps/backend/.env
    environment:
      - HOST_DB=db
      - HOST_QUEUE=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: apps/mobile/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
